### ISSUE TITLE
[Solved] The model is not being loaded

### ISSUE THREAD

**Issue by yousefan** [hugozanini/TFJS-object-detection#1]
After cloning the whole project and using your uploaded trained model the browser opens the webcam but it detects no kangaroos. I have tested several kangaroo images but none of them was detected. What is the problem

**Comment by hugozanini** [comment]
Hi @mahdiyousofun , thanks for your question.

It seems that the model was not loaded properly on your PC. Please verify if the model path in the [load_model](https://github.com/hugozanini/TFJS-object-detection/blob/1c169e4bbf6f9e321a1c54cb3a802398e6c7bdbc/src/index.js#L10) function is correct.

I've just tested the code in the Glitch app and everything is working fine. Please try to test it using the following link https://glitch.com/edit/#!/real-time-object-detection and let me know if you can recognize the kangaroos.

I did a test showing a photo from my mobile to the webcam and it worked well.
