### ISSUE TITLE
[Solved] How to leverage the Index.js for my custom classes(multiple). Will it work for my model.json pretrained using mobilenet v2_320*320 SSD ?

### ISSUE THREAD

**Issue by Anishauday** [hugozanini/TFJS-object-detection#7]
I tried reusing the .js files for my saved model and it wasn't detecting. I used transfer learning and retrained for my 4 custom classes.

**Comment by hugozanini** [comment]
Hey @Anishauday, could you be more specific about what's happening in your code?
