### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by sotiriskar** [hugozanini/TFJS-object-detection#8]
Any idea why i get that error in react.js. Everything else works great.

**Comment by SotirisKar** [comment]
I get the error in this part. Pretty much the code is same as yours except the "predictions[].arraySync();" for boxes,scores and classes because I load diffrent model.
        bbox[0] = minX;
        bbox[1] = minY;
        bbox[2] = maxX - minX;
        bbox[3] = maxY - minY;
        detectionObjects.push({
          class: classes[i],
----->label: classesDir[classes[i]].name,
          score: score.toFixed(4),
          bbox: bbox
        })
